name: Deploy eshop

on:
  workflow_dispatch:
  
jobs:
    - name: Code checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.WORKFLOW_TOKEN }}

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Ansible
      run: pip3 install ansible boto boto3

    - name: Execute playbook
      run: |
        ANSIBLE_HOST_KEY_CHECKING=False
        echo "${{ secrets.ANSIBLE_VAULT_PASS }}" > ~/.ssh/.ansible_vault_pass
        echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/devops.pem
        chmod 400 ~/.ssh/devops.pem
        ansible-playbook ansible/ec2_deploy.yml --vault-password-file ~/.ssh/.ansible_vault_pass --user ec2-user --key-file ~/.ssh/devops.pem