name: Deploy eshop

on:
  workflow_dispatch:
  
jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Code checkout
        uses: actions/checkout@v2.5.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Unset vars 
        run: |
          unset AWS_DEFAULT_REGION 
          unset AWS_REGION 
          unset AWS_ACCESS_KEY_ID 
          unset AWS_SECRET_ACCESS_KEY 
          unset AWS_SESSION_TOKEN

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          ec2-image-id: ami-0b0dcb5067f052a63
          ec2-instance-type: t2.micro
          subnet-id: subnet-05247750f1887b940
          security-group-id: sg-0afb63de08dbe09bc

  do-the-job:
    name: Do the job on the runner
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.label }}
    steps:
      - name: Hello World
        run: echo 'Hello World!'
